lang: ja
title: micro:bit ワークショップガイド
timezone: Asia/Tokyo
baseurl: /microbit-workshop-guide
theme: jekyll-theme-primer
plugins:
  # NOTE: Plugins allowed by GitHub Pages
  #   see also https://github.com/github/pages-gem/blob/509fad9b10941461225dacd3d1ec38042f7986c6/lib/github-pages/plugins.rb#L20-L42
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # FIXME: Dependency Error
  # - jekyll-include-cache
  - jekyll-octicons
  - jekyll-remote-theme
