name: fetch
on:
  schedule: [{ cron: "*/15 * * * *" }]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bin/fetch
      - id: git_status
        run: echo "::set-output name=mod::$(git status --porcelain)"
      - if: steps.git_status.outputs.mod != ''
        run: |
          git -c "user.name=bot" -c "user.email=bot@example" commit -a -m update-data \
          && git push origin HEAD
